# Generated by Django 4.2.6 on 2024-12-19 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='subtask',
        ),
        migrations.AddField(
            model_name='subtask',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='subtasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SubTaskDetail',
        ),
        migrations.DeleteModel(
            name='ToDoItem',
        ),
    ]
