# Generated by Django 4.2.6 on 2024-12-18 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_app', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='subtasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='task_app.subtask')),
            ],
        ),
    ]
